#1090


[General]
sim-time-limit = 5000000s
#repeat=30
description = "low job arrival rate"
network = SingleQueue
**.processor.bufferSize = 512
**.processor.CPUCapacity = 256
**.processor.MemoryCapacity = 256
**.processor.BandwidthCapacity = 256
**.processor.checkInterval = 0.1250s

**.processor.schedulingPolicy = "MostServerFit" # "FIFO", "Priority", "MostServerFit"

**.source[0].sourceId = "source0"
**.source[0].interarrivalTime = exponential(0.2646s)
**.source[0].serviceTime = exponential(1s)
**.source[0].requiredCPU = 1
**.source[0].requiredMemory = 1
**.source[0].requiredBandwidth = 1

**.source[1].sourceId = "source1"
**.source[1].interarrivalTime = exponential(2.381s)
**.source[1].serviceTime = exponential(10s)
**.source[1].requiredCPU = 64
**.source[1].requiredMemory = 64
**.source[1].requiredBandwidth = 64


**.source[*].processor.MsgDropped.record=vector
**.processor.msgProcessedSignal.record=vector
		